package tampilan;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.JOptionPane;
import javax.swing.SpinnerModel;
import java.sql.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.table.*;
import koneksi.*;

/*
 * TiketKeretaApi.java
 *
 * Created on Jun 5, 2021, 10:03:26 PM
 */
/**
 *
 * @author lynlala
 */
public class TiketKeretaApi extends javax.swing.JFrame {
    String nama = "";
    String umur = "";
    String dari = "";
    String tujuan = "";
//    String jml = "";
    String harga = "";
    String kelas = "";
    
    // database koneksi
    private Connection db = new Database().connect();
    
    // table model
    private DefaultTableModel table;
    
    /** Creates new form TiketKeretaApi */
    public TiketKeretaApi() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Kelas = new javax.swing.ButtonGroup();
        Harga = new javax.swing.ButtonGroup();
        Dari = new javax.swing.ButtonGroup();
        Tujuan = new javax.swing.ButtonGroup();
        jFrame1 = new javax.swing.JFrame();
        FormTiket = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Namapenumpang = new javax.swing.JTextField();
        Usia = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Jakarta = new javax.swing.JRadioButton();
        Bandung = new javax.swing.JRadioButton();
        Solo = new javax.swing.JRadioButton();
        Malang = new javax.swing.JRadioButton();
        Yogyakarta = new javax.swing.JRadioButton();
        Semarang = new javax.swing.JRadioButton();
        Kebumen = new javax.swing.JRadioButton();
        Tegal = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jakarta = new javax.swing.JRadioButton();
        bandung = new javax.swing.JRadioButton();
        solo = new javax.swing.JRadioButton();
        malang = new javax.swing.JRadioButton();
        yogyakarta = new javax.swing.JRadioButton();
        semarang = new javax.swing.JRadioButton();
        kebumen = new javax.swing.JRadioButton();
        tegal = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        Jumlahpenumpang = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        Ekonomi = new javax.swing.JCheckBox();
        Bisnis = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        empatpuluhlima = new javax.swing.JRadioButton();
        enampuluhlima = new javax.swing.JRadioButton();
        delapanpuluhlima = new javax.swing.JRadioButton();
        seratuslimapuluh = new javax.swing.JRadioButton();
        limapuluhlima = new javax.swing.JRadioButton();
        tujuhpuluhlima = new javax.swing.JRadioButton();
        sembilanpuluh = new javax.swing.JRadioButton();
        seratustujuhpuluh = new javax.swing.JRadioButton();
        Pesan = new javax.swing.JButton();
        Batal = new javax.swing.JButton();
        usiaHelp = new javax.swing.JLabel();
        TableData = new javax.swing.JScrollPane();
        tableData = new javax.swing.JTable();
        btnTampilData = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FormTiket.setAutoscrolls(true);
        FormTiket.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Train Ticket");

        jLabel2.setText("Nama Penumpang");

        jLabel3.setText("Usia");

        Namapenumpang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamapenumpangActionPerformed(evt);
            }
        });

        Usia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                UsiaKeyPressed(evt);
            }
        });

        jLabel4.setText("Dari");

        Dari.add(Jakarta);
        Jakarta.setText("Jakarta");
        Jakarta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JakartaActionPerformed(evt);
            }
        });

        Dari.add(Bandung);
        Bandung.setText("Bandung");
        Bandung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BandungActionPerformed(evt);
            }
        });

        Dari.add(Solo);
        Solo.setText("Solo");
        Solo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SoloActionPerformed(evt);
            }
        });

        Dari.add(Malang);
        Malang.setText("Malang");
        Malang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MalangActionPerformed(evt);
            }
        });

        Dari.add(Yogyakarta);
        Yogyakarta.setText("Yogyakarta");
        Yogyakarta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YogyakartaActionPerformed(evt);
            }
        });

        Dari.add(Semarang);
        Semarang.setText("Semarang");
        Semarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SemarangActionPerformed(evt);
            }
        });

        Dari.add(Kebumen);
        Kebumen.setText("Kebumen");
        Kebumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KebumenActionPerformed(evt);
            }
        });

        Dari.add(Tegal);
        Tegal.setText("Tegal");
        Tegal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TegalActionPerformed(evt);
            }
        });

        jLabel5.setText("Tujuan");

        Tujuan.add(jakarta);
        jakarta.setText("Jakarta");
        jakarta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jakartaActionPerformed(evt);
            }
        });

        Tujuan.add(bandung);
        bandung.setText("Bandung");
        bandung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bandungActionPerformed(evt);
            }
        });

        Tujuan.add(solo);
        solo.setText("solo");
        solo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soloActionPerformed(evt);
            }
        });

        Tujuan.add(malang);
        malang.setText("Malang");
        malang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                malangActionPerformed(evt);
            }
        });

        Tujuan.add(yogyakarta);
        yogyakarta.setText("Yogyakarta");
        yogyakarta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yogyakartaActionPerformed(evt);
            }
        });

        Tujuan.add(semarang);
        semarang.setText("Semarang");
        semarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semarangActionPerformed(evt);
            }
        });

        Tujuan.add(kebumen);
        kebumen.setText("Kebumen");
        kebumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kebumenActionPerformed(evt);
            }
        });

        Tujuan.add(tegal);
        tegal.setText("Tegal");
        tegal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tegalActionPerformed(evt);
            }
        });

        jLabel6.setText("Jumlah Penumpang");

        jLabel7.setText("Kelas");

        Kelas.add(Ekonomi);
        Ekonomi.setText("Ekonomi");
        Ekonomi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EkonomiActionPerformed(evt);
            }
        });

        Kelas.add(Bisnis);
        Bisnis.setText("Bisnis");
        Bisnis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BisnisActionPerformed(evt);
            }
        });

        jLabel8.setText("Harga");

        Harga.add(empatpuluhlima);
        empatpuluhlima.setText("Rp.45.000");
        empatpuluhlima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empatpuluhlimaActionPerformed(evt);
            }
        });

        Harga.add(enampuluhlima);
        enampuluhlima.setText("Rp.65.000");
        enampuluhlima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enampuluhlimaActionPerformed(evt);
            }
        });

        Harga.add(delapanpuluhlima);
        delapanpuluhlima.setText("Rp.85.000");
        delapanpuluhlima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delapanpuluhlimaActionPerformed(evt);
            }
        });

        Harga.add(seratuslimapuluh);
        seratuslimapuluh.setText("Rp.150.000");
        seratuslimapuluh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seratuslimapuluhActionPerformed(evt);
            }
        });

        Harga.add(limapuluhlima);
        limapuluhlima.setText("Rp.55.000");
        limapuluhlima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limapuluhlimaActionPerformed(evt);
            }
        });

        Harga.add(tujuhpuluhlima);
        tujuhpuluhlima.setText("Rp.75.000");
        tujuhpuluhlima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tujuhpuluhlimaActionPerformed(evt);
            }
        });

        Harga.add(sembilanpuluh);
        sembilanpuluh.setText("Rp.90.000");
        sembilanpuluh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sembilanpuluhActionPerformed(evt);
            }
        });

        Harga.add(seratustujuhpuluh);
        seratustujuhpuluh.setText("Rp.170.000");
        seratustujuhpuluh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seratustujuhpuluhActionPerformed(evt);
            }
        });

        Pesan.setText("Pesan");
        Pesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesanActionPerformed(evt);
            }
        });

        Batal.setText("Batal");
        Batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BatalActionPerformed(evt);
            }
        });

        tableData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Nama", "Usia", "Dari", "Tujuan", "Jumlah penumpang", "Kelas", "Harga"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableData.setViewportView(tableData);
        if (tableData.getColumnModel().getColumnCount() > 0) {
            tableData.getColumnModel().getColumn(0).setPreferredWidth(36);
            tableData.getColumnModel().getColumn(1).setPreferredWidth(200);
            tableData.getColumnModel().getColumn(5).setPreferredWidth(150);
        }

        btnTampilData.setText("Tampilkan Data");
        btnTampilData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTampilDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FormTiketLayout = new javax.swing.GroupLayout(FormTiket);
        FormTiket.setLayout(FormTiketLayout);
        FormTiketLayout.setHorizontalGroup(
            FormTiketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FormTiketLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FormTiketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(FormTiketLayout.createSequentialGroup()
                        .addGroup(FormTiketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addGroup(FormTiketLayout.createSequentialGroup()
                                .addComponent(Pesan)
                                .addGap(18, 18, 18)
                                .addComponent(Batal)))
                        .addGap(18, 18, 18)
                        .addGroup(FormTiketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FormTiketLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnTampilData))
                            .addGroup(FormTiketLayout.createSequentialGroup()
                                .addGroup(FormTiketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(usiaHelp)
                                    .addGroup(FormTiketLayout.createSequentialGroup()
                                        .addGroup(FormTiketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Bandung)
                                            .addComponent(Jakarta)
                                            .addComponent(bandung)
                                            .addComponent(jakarta))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(FormTiketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(FormTiketLayout.createSequentialGroup()
                                                .addGroup(FormTiketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(malang)
                                                    .addComponent(solo))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(FormTiketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(yogyakarta)
                                                    .addComponent(semarang))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(FormTiketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(tegal)
                                                    .addComponent(kebumen)))
                                            .addGroup(FormTiketLayout.createSequentialGroup()
                                                .addGroup(FormTiketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(Malang)
                                                    .addComponent(Solo))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(FormTiketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(Yogyakarta)
                                                    .addComponent(Semarang))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(FormTiketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(Tegal)
                                                    .addComponent(Kebumen)))))
                                    .addComponent(Jumlahpenumpang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(FormTiketLayout.createSequentialGroup()
                                        .addComponent(empatpuluhlima)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(enampuluhlima)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(delapanpuluhlima)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(seratuslimapuluh))
                                    .addGroup(FormTiketLayout.createSequentialGroup()
                                        .addComponent(Ekonomi)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Bisnis))
                                    .addGroup(FormTiketLayout.createSequentialGroup()
                                        .addGap(158, 158, 158)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Namapenumpang, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Usia, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(FormTiketLayout.createSequentialGroup()
                                        .addComponent(limapuluhlima)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tujuhpuluhlima)
                                        .addGap(2, 2, 2)
                                        .addComponent(sembilanpuluh)
                                        .addGap(53, 53, 53)
                                        .addComponent(seratustujuhpuluh)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(FormTiketLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(TableData, javax.swing.GroupLayout.PREFERRED_SIZE, 749, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(185, 185, 185))
        );
        FormTiketLayout.setVerticalGroup(
            FormTiketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormTiketLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(FormTiketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Namapenumpang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FormTiketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Usia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usiaHelp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FormTiketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Jakarta)
                    .addComponent(Solo)
                    .addComponent(Yogyakarta)
                    .addComponent(Kebumen))
                .addGroup(FormTiketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FormTiketLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(FormTiketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Bandung)
                            .addComponent(Malang)
                            .addComponent(Semarang)
                            .addComponent(Tegal))
                        .addGap(19, 19, 19)
                        .addGroup(FormTiketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jakarta)
                            .addComponent(solo)
                            .addComponent(yogyakarta)
                            .addComponent(kebumen))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(FormTiketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bandung)
                            .addComponent(malang)
                            .addComponent(tegal)
                            .addComponent(semarang)))
                    .addGroup(FormTiketLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel5)))
                .addGap(11, 11, 11)
                .addGroup(FormTiketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FormTiketLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel7))
                    .addGroup(FormTiketLayout.createSequentialGroup()
                        .addComponent(Jumlahpenumpang, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(FormTiketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Ekonomi)
                            .addComponent(Bisnis))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FormTiketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(empatpuluhlima)
                    .addComponent(enampuluhlima)
                    .addComponent(delapanpuluhlima)
                    .addComponent(seratuslimapuluh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FormTiketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(limapuluhlima)
                    .addComponent(tujuhpuluhlima)
                    .addComponent(sembilanpuluh)
                    .addComponent(seratustujuhpuluh))
                .addGap(32, 32, 32)
                .addGroup(FormTiketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Batal)
                    .addComponent(Pesan)
                    .addComponent(btnTampilData))
                .addGap(34, 34, 34)
                .addComponent(TableData, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(317, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(FormTiket, javax.swing.GroupLayout.PREFERRED_SIZE, 756, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(FormTiket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void NamapenumpangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamapenumpangActionPerformed
// TODO add your handling code here:
    nama = evt.getActionCommand();
}//GEN-LAST:event_NamapenumpangActionPerformed

private void JakartaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JakartaActionPerformed
// TODO add your handling code here:
    dari = evt.getActionCommand();
}//GEN-LAST:event_JakartaActionPerformed

private void BandungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BandungActionPerformed
// TODO add your handling code here:
    dari = evt.getActionCommand();
}//GEN-LAST:event_BandungActionPerformed

private void EkonomiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EkonomiActionPerformed
// TODO add your handling code here:
    kelas = evt.getActionCommand();
}//GEN-LAST:event_EkonomiActionPerformed

private void PesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesanActionPerformed
    // TODO add your handling code here:
    nama = Namapenumpang.getText();
    umur = Usia.getText();
    SpinnerModel jml = Jumlahpenumpang.getModel();
    int minOrder = 1;
    
    
    if (nama.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Nama tidak boleh kosong");
    }
    else if (umur.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Umur tidak boleh kosong");
    }
    else if (dari.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Silahkan tentukan dari mana anda berangkat.");
    }
    else if (tujuan.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Silahkan tentukan kota tujuan anda.");
    }
    else if (jml.getValue().hashCode() < minOrder) {
        JOptionPane.showMessageDialog(this, "Silahkan tentukan jumlah penumpang.");
    }
    else if (kelas.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Silahkan tentukan mau make kelas yang mana?");
    }
    else if (harga.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Silahkan tentukan biaya keberangkatan anda.");
    }
    else {
        // JOptionPane.showMessageDialog(this, "Nama: " + nama + "\nUmur: " + umur + "\nDari: " + dari + "\nTujuan: " + tujuan + "\nJumlah penumpang: " + jml.getValue() + "\nKelas: " + kelas + "\nHarga: " + harga);
        try {
            Statement state = db.createStatement();
            final String regex = "([\\d].+)";
            final Pattern pattern = Pattern.compile(regex);
            final Matcher matcher = pattern.matcher(harga);
            
            while (matcher.find()) {
                for (int i = 1; i <= matcher.groupCount(); i++) {
                    harga = matcher.group(i);
                }
            }
            
            harga = harga.replaceAll("\\.", "");
            
            String sql = "INSERT INTO struk(nama,usia,dari,tujuan,jumlah_penumpang,kelas,harga) VALUES ('" + nama + "','" + umur + "','" + dari + "','" + tujuan + "','" + jml.getValue() + "','" + kelas + "','" + harga.replaceAll("/(.*)/", "") + "')";
            
            state.executeUpdate(sql);
            state.close();
            JOptionPane.showMessageDialog(this, "Berhasil menambahkan data.");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
}//GEN-LAST:event_PesanActionPerformed

private void empatpuluhlimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empatpuluhlimaActionPerformed
// TODO add your handling code here:
    harga = evt.getActionCommand();
}//GEN-LAST:event_empatpuluhlimaActionPerformed

private void BisnisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BisnisActionPerformed
// TODO add your handling code here:
    kelas = evt.getActionCommand();
}//GEN-LAST:event_BisnisActionPerformed

    private void SoloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SoloActionPerformed
        // TODO add your handling code here:
        dari = evt.getActionCommand();
    }//GEN-LAST:event_SoloActionPerformed

    private void YogyakartaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YogyakartaActionPerformed
        // TODO add your handling code here:
        dari = evt.getActionCommand();
    }//GEN-LAST:event_YogyakartaActionPerformed

    private void KebumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KebumenActionPerformed
        // TODO add your handling code here:
        dari = evt.getActionCommand();
    }//GEN-LAST:event_KebumenActionPerformed

    private void MalangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MalangActionPerformed
        // TODO add your handling code here:
        dari = evt.getActionCommand();
    }//GEN-LAST:event_MalangActionPerformed

    private void SemarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SemarangActionPerformed
        // TODO add your handling code here:
        dari = evt.getActionCommand();
    }//GEN-LAST:event_SemarangActionPerformed

    private void TegalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TegalActionPerformed
        // TODO add your handling code here:
        dari = evt.getActionCommand();
    }//GEN-LAST:event_TegalActionPerformed

    private void jakartaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jakartaActionPerformed
        // TODO add your handling code here:
        tujuan = evt.getActionCommand();
    }//GEN-LAST:event_jakartaActionPerformed

    private void soloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soloActionPerformed
        // TODO add your handling code here:
        tujuan = evt.getActionCommand();
    }//GEN-LAST:event_soloActionPerformed

    private void yogyakartaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yogyakartaActionPerformed
        // TODO add your handling code here:
        tujuan = evt.getActionCommand();
    }//GEN-LAST:event_yogyakartaActionPerformed

    private void kebumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kebumenActionPerformed
        // TODO add your handling code here:
        tujuan = evt.getActionCommand();
    }//GEN-LAST:event_kebumenActionPerformed

    private void bandungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bandungActionPerformed
        // TODO add your handling code here:
        tujuan = evt.getActionCommand();
    }//GEN-LAST:event_bandungActionPerformed

    private void malangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_malangActionPerformed
        // TODO add your handling code here:
        tujuan = evt.getActionCommand();
    }//GEN-LAST:event_malangActionPerformed

    private void semarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semarangActionPerformed
        // TODO add your handling code here:
        tujuan = evt.getActionCommand();
    }//GEN-LAST:event_semarangActionPerformed

    private void tegalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tegalActionPerformed
        // TODO add your handling code here:
        tujuan = evt.getActionCommand();
    }//GEN-LAST:event_tegalActionPerformed

    private void enampuluhlimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enampuluhlimaActionPerformed
        // TODO add your handling code here:
        harga = evt.getActionCommand();
    }//GEN-LAST:event_enampuluhlimaActionPerformed

    private void delapanpuluhlimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delapanpuluhlimaActionPerformed
        // TODO add your handling code here:
        harga = evt.getActionCommand();
    }//GEN-LAST:event_delapanpuluhlimaActionPerformed

    private void seratuslimapuluhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seratuslimapuluhActionPerformed
        // TODO add your handling code here:
        harga = evt.getActionCommand();
    }//GEN-LAST:event_seratuslimapuluhActionPerformed

    private void limapuluhlimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limapuluhlimaActionPerformed
        // TODO add your handling code here:
        harga = evt.getActionCommand();
    }//GEN-LAST:event_limapuluhlimaActionPerformed

    private void tujuhpuluhlimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tujuhpuluhlimaActionPerformed
        // TODO add your handling code here:
        harga = evt.getActionCommand();
    }//GEN-LAST:event_tujuhpuluhlimaActionPerformed

    private void sembilanpuluhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sembilanpuluhActionPerformed
        // TODO add your handling code here:
        harga = evt.getActionCommand();
    }//GEN-LAST:event_sembilanpuluhActionPerformed

    private void seratustujuhpuluhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seratustujuhpuluhActionPerformed
        // TODO add your handling code here:
        harga = evt.getActionCommand();
    }//GEN-LAST:event_seratustujuhpuluhActionPerformed

    private void BatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BatalActionPerformed
        // TODO add your handling code here:
        Namapenumpang.setText("");
        Usia.setText("");
        Dari.clearSelection();
        Tujuan.clearSelection();
        Jumlahpenumpang.getModel().setValue(0);
        Kelas.clearSelection();
        Harga.clearSelection();
    }//GEN-LAST:event_BatalActionPerformed

    private void UsiaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UsiaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
            usiaHelp.setText("");
        } else {
            if (evt.getKeyChar() <= '9') {
                usiaHelp.setText("");
            } else {
                usiaHelp.setText("Please enter only number!!!");
            }
        }
    }//GEN-LAST:event_UsiaKeyPressed

    private void btnTampilDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTampilDataActionPerformed
        table = (DefaultTableModel) tableData.getModel();
        table.getDataVector().removeAllElements();
        table.fireTableDataChanged();
        
        try {
            Statement state = db.createStatement();
            
            String sql = "SELECT * FROM struk ORDER BY 'id_struk' DESC LIMIT 10";
            ResultSet response = state.executeQuery(sql);
            
            while (response.next()) {
                Object[] obj = new Object[8];
                
                obj[0] = response.getString("id_struk");
                obj[1] = response.getString("nama");
                obj[2] = response.getString("usia");
                obj[3] = response.getString("dari");
                obj[4] = response.getString("tujuan");
                obj[5] = response.getString("jumlah_penumpang");
                obj[6] = response.getString("kelas");
                obj[7] = response.getString("harga");
                
                table.addRow(obj);
            }
            
            state.close();
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnTampilDataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TiketKeretaApi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TiketKeretaApi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TiketKeretaApi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TiketKeretaApi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TiketKeretaApi().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Bandung;
    private javax.swing.JButton Batal;
    private javax.swing.JCheckBox Bisnis;
    private javax.swing.ButtonGroup Dari;
    private javax.swing.JCheckBox Ekonomi;
    private javax.swing.JPanel FormTiket;
    private javax.swing.ButtonGroup Harga;
    private javax.swing.JRadioButton Jakarta;
    private javax.swing.JSpinner Jumlahpenumpang;
    private javax.swing.JRadioButton Kebumen;
    private javax.swing.ButtonGroup Kelas;
    private javax.swing.JRadioButton Malang;
    private javax.swing.JTextField Namapenumpang;
    private javax.swing.JButton Pesan;
    private javax.swing.JRadioButton Semarang;
    private javax.swing.JRadioButton Solo;
    private javax.swing.JScrollPane TableData;
    private javax.swing.JRadioButton Tegal;
    private javax.swing.ButtonGroup Tujuan;
    private javax.swing.JTextField Usia;
    private javax.swing.JRadioButton Yogyakarta;
    private javax.swing.JRadioButton bandung;
    private javax.swing.JButton btnTampilData;
    private javax.swing.JRadioButton delapanpuluhlima;
    private javax.swing.JRadioButton empatpuluhlima;
    private javax.swing.JRadioButton enampuluhlima;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jakarta;
    private javax.swing.JRadioButton kebumen;
    private javax.swing.JRadioButton limapuluhlima;
    private javax.swing.JRadioButton malang;
    private javax.swing.JRadioButton semarang;
    private javax.swing.JRadioButton sembilanpuluh;
    private javax.swing.JRadioButton seratuslimapuluh;
    private javax.swing.JRadioButton seratustujuhpuluh;
    private javax.swing.JRadioButton solo;
    private javax.swing.JTable tableData;
    private javax.swing.JRadioButton tegal;
    private javax.swing.JRadioButton tujuhpuluhlima;
    private javax.swing.JLabel usiaHelp;
    private javax.swing.JRadioButton yogyakarta;
    // End of variables declaration//GEN-END:variables
}
